version: '3'

services:
  server:
    image: containous/whoami
    restart: always
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:127.0.0.1"
      - "traefik.frontend.rule=PathPrefixStrip:/whoami"
      - "traefik.frontend.entryPoints=http"
    networks:
      - web

networks:
  web:
    external: true
