version: '3'

services:
  db:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ./volumes/var/lib/mysql:/var/lib/mysql
    networks:
      - docker_services

networks:
  docker_services:
    external: true
