version: '3'

services:
  db:
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./volumes/var/lib/postgresql/data:/var/lib/postgresql/data
    # networks:
    #   - docker_services

# networks:
#   docker_services:
#     external: true
